version: "3.3"

services:
  minecraft:
    image: fc4aab23cb1c
    container_name: "fabric-mcserver"
    network_mode: host
    environment:
      MEMORYSIZE: "8G"
    volumes:
      - "/home/sib/appdata/GC-Modded-Server:/data:rw"
#    ports:
        # Minecraft
#      - "25565:25565"     
        # Dynmap 
#      - "8123:8123"
        # Prox chat
#      - "24454:24454"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
